# Rain configurations.
Rain:
  # Here you can specify the world to rain.
  # You can also use "PLAYER" to rain on the
  # world that this player are.
  #
  # Or just use your world name.
  world: "PLAYER"

  # The rain duration.
  duration: 60 # In seconds.

  # The money that the player should pay
  # to let it rain.
  pay-amount: 250.10

  # Is thundering allowed?
  thundering: false

  # Is storm allowed?
  storm: true

# Messages.
Messages:
  already-raining: "&cSomeone paid for rain already, try again in %rain_remaining%!"
  no-enough-money: "&cYou do not have enough money."
  rain-enabled:
    - '&bRain has been activated in this'
    - '&bworld for &71 minute&b!'

  # Boolean translations.
  boolean-on: "On"
  boolean-off: "Off"

  # Command Messages.
  help: # Command aliases: {timedrain, rain}
    - ''
    - '&aRain Commands:'
    - '&e/paidrain &b: Enable rain in a specific world.'
    - '&e/paidrain help &b: Sends this help message again.'
    - '&e/paidrain menu &b: Opens the rain menu.'
    - '&e/paidrain stats/status &b: Verify the Rain status.'
    - ''

  status:
    - ''
    - '&7Total money spent in rains: &6%money-spent%'
    - '&7Is rain activated: %is-raining%'
    - ''

# The rain menu.
Menu:
  info:
    title: "&7Paid Rain"
    rows: 3 # This number will be multiplied by 9.
  items:
    1:
      type: "STAINED_GLASS_PANE:7"
      name: ""
      lore: {}
      slot: "0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26"
    2:
      type: "WATER_BUCKET"
      name: "&bLet it rain"
      lore:
        - '&7Click here to let the'
        - '&7world rain for &b1 minute&7!'
        - ''
        - '&7Cost: &6250.1$ in game coins.'
      glow: true
      slot: 11
      action: "START_RAIN"
    3:
      type: "SIGN"
      name: "&5Statistics"
      lore:
        - '&7This server has spent'
        - '&6%money-spent%$ in game coins'
        - '&7in rain.'
        - ''
        - '&7Rain Status: %is-raining%'
      slot: 15